src/Teclyn/Teclyn.SampleMvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StructureMap.Attributes;
using StructureMap.Building;
using Teclyn.Core.Ioc;
using Teclyn.Core.Storage;
using Teclyn.SampleCore.TodoLists.Models;
using Teclyn.SampleMvc.Models;

namespace Teclyn.SampleMvc.Controllers
{
    public class HomeController : Controller
    {
        private IRepository<ITodoList> _todoLists;

        public HomeController(IRepository<ITodoList> repository, IRepository<ITodoList> todoLists)
        {
            this._todoLists = todoLists;
            //this.TodoLists = repository;
        }

        public ActionResult Index()
        {
            var model = new HomeModel
            {
                TodoLists = this._todoLists.ToList()
            };


            return View(model);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

src/Teclyn/Teclyn.SampleMvc/Controllers/TodoListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using StructureMap.Attributes;
using Teclyn.AspNetMvc.Models;
using Teclyn.Core.Ioc;
using Teclyn.Core.Storage;
using Teclyn.SampleCore.TodoLists.Models;
using Teclyn.SampleCore.Todos.Models;
using Teclyn.SampleMvc.Models;

namespace Teclyn.SampleMvc.Controllers
{
    public class TodoListController : Controller
    {
        private IRepository<ITodoList> _todoLists;

        public TodoListController(IRepository<ITodoList> todoLists, IRepository<ITodo> todos)
        {
            this._todoLists = todoLists;
            this._todos = todos;
        }

        private IRepository<ITodo> _todos;

        // GET: TodoList
        public async Task<ActionResult> Index(string id, int? s)
        {
            var todoList = await this._todoLists.GetByIdOrNull(id);

            if (todoList == null)
            {
                var todoLists = new ListModel<ITodoList>(
                    this._todoLists.OrderByDescending(c => c.CreationDate),
                    index => this.Url.Action("Index", new { s = index }),
                    s.GetValueOrDefault(),
                    20);

                return View(todoLists);
            }
            else
            {
                var model = new TodoListModel
                {
                    TodoList = todoList,
                    Todos = this._todos.Where(t => t.TodoList.Id == todoList.Id),
                };

                return View("Get", model);
            }
        }
    }
}

src/Teclyn/Teclyn.SampleMvc/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

src/Teclyn/Teclyn.SampleMvc/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/Teclyn/Teclyn.SampleMvc/Views/Home/Index.cshtml
@using Teclyn.SampleCore.TodoLists.Commands
@using Teclyn.SampleCore.TodoLists.Models
@model Teclyn.SampleMvc.Models.HomeModel
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>TECLYN</h1>
    <p class="lead">TECLYN is a toolkit aimed at building well architectured, business driven, scalable software. It uses concepts taken from CQRS, Domain Driven Design (DDD) and Event Sourcing.</p>
    <p><a href="https://github.com/klejeune/teclyn" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>


<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Todo Lists</h2>
        <ul>
            @foreach (var list in Model.TodoLists)
            {
                <li>@Html.ActionLink(list, "Index", "TodoList")</li>
            }
        </ul>

        <p><a class="btn btn-default" href="@Url.Action("Index", "TodoList")">Display more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Create a new Todo List</h2>
        <div>
            @using (var form = Html.CommandForm<CreateTodoListCommand>(true))
            {
                @form.Property(command => command.Name)
                @form.Submit("Create", "btn btn-primary")
            }
        </div>
        <div>
            @(Html.CommandButton<CreateTodoListCommand>("Create", command => command.Name = "Test", "btn btn-primary"))
        </div>
    </div>
</div>